### ISSUE TITLE
[Web] Test tracking

### ISSUE THREAD

**Issue by OmriHarary** [OmriHarary/QIES-redux#28]
Tracking implementation of currently missing tests

### QIES.Web
- [x] Controllers
  - [x] UsersController
    - [x] Login e062a88631ddd65b1266a36b33ca6c15bd5b3262
    - [x] Logout aecbe42b71794be061c50fa5d61ce33dcf3dbe73
  - [x] ServicesController
    - [x] CreateService 463c3b83c8c1d6d2d7539a0ac9789a3d17ee584e
    - [x] DeleteService 463c3b83c8c1d6d2d7539a0ac9789a3d17ee584e
    - [x] SellOrChangeTicket 82417295a95b6501a2b6bfdbc314dbe9565178e6
    - [x] CancelTicket caf479dce6ddff670137d66644a21417520b160f

### QIES.Core
- [x] LoginService fb7e498c83869b4d5aec8eb6a3f4368598d7fd60
- [x] LogoutService f16796a4490339335abc004af84e785284c4d809
- [x] Transactions
  - [x] CancelTicketsTransaction caf479dce6ddff670137d66644a21417520b160f
  - [x] CreateServiceTransaction 9e7c1824127f31ebfd1cb5b1c1c76c86a6846075
  - [x] DeleteServiceTransaction 9e7c1824127f31ebfd1cb5b1c1c76c86a6846075
  - [x] ChangeTicketsTransaction 82417295a95b6501a2b6bfdbc314dbe9565178e6
  - [x] SellTicketsTransaction 82417295a95b6501a2b6bfdbc314dbe9565178e6
